version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DATABSE=instagram
      - POSTGRES_DB=instagram
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - "54320:5432"
    network_mode: bridge
   
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.apigateway
    image: api-gateway
    env_file: ./packages/api-gateway/.env
    environment:
      - HOST_ADDRESS=postgres_db
      - PG_PORT=5432
    ports:
      - "5000:5000"
    network_mode: bridge
    links:
      - postgres

  user-service:
    build:
      context: .
      dockerfile: Dockerfile.userservice
    image: user-service
    environment:
      - HOST_ADDRESS=postgres_db
      - PG_PORT=5432
    ports:
      - "5001:5001"
    network_mode: bridge
    links:
      - postgres    
  
  image-service:
    build:
      context: .
      dockerfile: Dockerfile.imageservice
    image: image-service
    environment:
      - HOST_ADDRESS=postgres_db
      - PG_PORT=5432
    ports:
      - "5002:5002"
    network_mode: bridge
    links:
      - postgres          

  post-service:
    build:
      context: .
      dockerfile: Dockerfile.postservice
    image: post-service
    environment:
      - HOST_ADDRESS=postgres_db
      - PG_PORT=5432
    ports:
      - "5003:5003"
    network_mode: bridge
    links:
      - postgres  


volumes:
  db-data:
    driver: local